/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ImportRouteImport } from './routes/import'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PracticeSetupRouteImport } from './routes/practice-setup'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as WordbooksRouteImport } from './routes/wordbooks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSetupRoute = PracticeSetupRouteImport.update({
  id: '/practice-setup',
  path: '/practice-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const WordbooksRoute = WordbooksRouteImport.update({
  id: '/wordbooks',
  path: '/wordbooks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/favorites': typeof FavoritesRoute
  '/import': typeof ImportRoute
  '/mistakes': typeof MistakesRoute
  '/practice': typeof PracticeRoute
  '/practice-setup': typeof PracticeSetupRoute
  '/summary': typeof SummaryRoute
  '/wordbooks': typeof WordbooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/favorites': typeof FavoritesRoute
  '/import': typeof ImportRoute
  '/mistakes': typeof MistakesRoute
  '/practice': typeof PracticeRoute
  '/practice-setup': typeof PracticeSetupRoute
  '/summary': typeof SummaryRoute
  '/wordbooks': typeof WordbooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/favorites': typeof FavoritesRoute
  '/import': typeof ImportRoute
  '/mistakes': typeof MistakesRoute
  '/practice': typeof PracticeRoute
  '/practice-setup': typeof PracticeSetupRoute
  '/summary': typeof SummaryRoute
  '/wordbooks': typeof WordbooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exam'
    | '/favorites'
    | '/import'
    | '/mistakes'
    | '/practice'
    | '/practice-setup'
    | '/summary'
    | '/wordbooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exam'
    | '/favorites'
    | '/import'
    | '/mistakes'
    | '/practice'
    | '/practice-setup'
    | '/summary'
    | '/wordbooks'
  id:
    | '__root__'
    | '/'
    | '/exam'
    | '/favorites'
    | '/import'
    | '/mistakes'
    | '/practice'
    | '/practice-setup'
    | '/summary'
    | '/wordbooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamRoute: typeof ExamRoute
  FavoritesRoute: typeof FavoritesRoute
  ImportRoute: typeof ImportRoute
  MistakesRoute: typeof MistakesRoute
  PracticeRoute: typeof PracticeRoute
  PracticeSetupRoute: typeof PracticeSetupRoute
  SummaryRoute: typeof SummaryRoute
  WordbooksRoute: typeof WordbooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-setup': {
      id: '/practice-setup'
      path: '/practice-setup'
      fullPath: '/practice-setup'
      preLoaderRoute: typeof PracticeSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wordbooks': {
      id: '/wordbooks'
      path: '/wordbooks'
      fullPath: '/wordbooks'
      preLoaderRoute: typeof WordbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamRoute: ExamRoute,
  FavoritesRoute: FavoritesRoute,
  ImportRoute: ImportRoute,
  MistakesRoute: MistakesRoute,
  PracticeRoute: PracticeRoute,
  PracticeSetupRoute: PracticeSetupRoute,
  SummaryRoute: SummaryRoute,
  WordbooksRoute: WordbooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
